service: raven-ms-lambda-regionalization
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    # If you use Yarn instead of NPM in your environment, uncomment the following line.
    # packager: yarn

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

functions:
  getEvents:
    handler: handlers/core.getEvents
    environment:
      ENVIRONMENT: demo
    events: # All events associated with this function
      - http:
          path: calendar/{calendarEvent}
          method: get
          request:
            parameters:
              paths:
                calendarEvent: true
